CREATE DATABASE SocialDB


USE SocialDB


CREATE TABLE Users(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] NVARCHAR(MAX) NOT NULL,
[Surname] NVARCHAR(MAX) NOT NULL,
[Age] INT NOT NULL,
[Username] NVARCHAR(MAX) NOT NULL,
[Password] NVARCHAR(MAX) NOT NULL,
[Email] NVARCHAR(MAX) NOT NULL,
[PhoneNumber] NVARCHAR(MAX) NOT NULL,
[ImagePath] NVARCHAR(MAX)  NOT NULL
)

CREATE TABLE Stories(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
[ImagePath] NVARCHAR(MAX) NOT NULL,
[BackgroundImage] NVARCHAR(MAX) NOT NULL,
[CreatedTime] DATETIME2 NOT NULL,
[Message] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Comments(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
[Message] NVARCHAR(MAX) NOT NULL,
[DatePost] DATETIME2  NOT NULL DEFAULT(SYSDATETIME()),
[Like] INT NOT NULL DEFAULT(0)
)

CREATE TABLE Posts(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT  FOREIGN KEY REFERENCES Users(Id) NOT NULL,
[CommentId] INT FOREIGN KEY REFERENCES Comments(Id) NOT NULL,
[Message] NVARCHAR(MAX) NOT NULL,
[ImagePath] NVARCHAR(MAX) NOT NULL,
[CreatedTime] DATETIME2 NOT NULL DEFAULT(SYSDATETIME()),
[Like] INT NOT NULL DEFAULT(0)
)

CREATE TABLE Groups(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] NVARCHAR(MAX) NOT NULL,
[CreatedTime] DATETIME2  DEFAULT(SYSDATETIME()) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
)

CREATE TABLE Notifications(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
[Message] NVARCHAR(MAX) NOT NULL,
[CurrentTime] DATETIME2 DEFAULT(SYSDATETIME()) NOT NULL
)

CREATE TABLE Chats(
[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
[Message] NVARCHAR(MAX) NOT NULL,
[ImagePath] NVARCHAR(MAX) NOT NULL,
[SendedTime] DATETIME2 DEFAULT(SYSDATETIME()) NOT NULL
)




